name: music-tag-backend

services:
  backend: 
    build:
      context: .
      dockerfile: application.dockerfile
    container_name: music-tag-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - IP=${IP}
      - DATABASE_URL=${DOCKER_MONGO_DB_URL}
      - ENV=${ENV}
    volumes:
      - ./music_data:${MUSIC_FILE_HOST_PATH}
    depends_on:
      - database
  

  database:
    image: mongodb/mongodb-community-server:latest
    hostname: mongodb 
    container_name: music-tag-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
    driver: local