let composerList = [
    { fName: "Eban", mName: "Immanuel", lName: "Schletter", suffix: "", pro: "BMI", cae: "185941044"},
{ fName: "Alan", mName: "E", lName: "Williams", suffix: "", pro: "BMI", cae: "231693574"},
{ fName: "Helen", mName: "", lName: "Simmins McMillin", suffix: "", pro: "BMI", cae: "421417889"},
{ fName: "Rene", mName: "F", lName: "Van Verseveld", suffix: "", pro: "BMI", cae: "216284187"},
{ fName: "Stefanie", mName: "Joy", lName: "Sellars", suffix: "", pro: "BMI", cae: "400673002"},
{ fName: "Timothy", mName: "Robert", lName: "Eckert", suffix: "", pro: "BMI", cae: "448061851"},
{ fName: "Anfinn", mName: "", lName: "Skulevold", suffix: "", pro: "BMI", cae: "254363177"},
{ fName: "Antonio", mName: "", lName: "Agapiou", suffix: "", pro: "BMI", cae: "501269977"},
{ fName: "Bryan", mName: "Timothy", lName: "Parker", suffix: "", pro: "BMI", cae: "500348891"},
{ fName: "Dana", mName: "Ryan", lName: "Parker", suffix: "", pro: "BMI", cae: "196522742"},
{ fName: "David", mName: "", lName: "Zumsteg", suffix: "", pro: "BMI", cae: "345713758"},
{ fName: "John", mName: "J", lName: "Arky", suffix: "", pro: "BMI", cae: "182179262"},
{ fName: "Matthew", mName: "Alan", lName: "Vowles", suffix: "", pro: "BMI", cae: "400336122"},
{ fName: "Walter", mName: "Robert", lName: "Thompson", suffix: "Jr", pro: "BMI", cae: "182042398"},
{ fName: "Andrew", mName: "Edward", lName: "Furrer", suffix: "", pro: "BMI", cae: "494878190"},
{ fName: "Harold", mName: "Alexander", lName: "Stephens", suffix: "Jr", pro: "BMI", cae: "400856876"},
{ fName: "John", mName: "De Sales", lName: "Murphy", suffix: "", pro: "BMI", cae: "353705271"},
{ fName: "Michael", mName: "Vache", lName: "Jamgochian", suffix: "", pro: "BMI", cae: "490382642"},
{ fName: "Michael", mName: "Steven", lName: "Mahan", suffix: "", pro: "BMI", cae: "210469696"},
{ fName: "Philip", mName: "Andrew", lName: "Lockwood", suffix: "", pro: "BMI", cae: "459349905"},
{ fName: "Steve", mName: "D", lName: "Postel", suffix: "", pro: "BMI", cae: "227193178"},
{ fName: "Tad", mName: "", lName: "Wadhams", suffix: "", pro: "BMI", cae: "185266742"},
{ fName: "Nick", mName: "", lName: "Pierone", suffix: "", pro: "BMI", cae: "199745994"},
{ fName: "Linda", mName: "Komer", lName: "Polan", suffix: "", pro: "BMI", cae: "530688741"},
{ fName: "Michael", mName: "", lName: "Now", suffix: "", pro: "BMI", cae: "356090169"},
{ fName: "Kevin", mName: "Thomas", lName: "Longden", suffix: "", pro: "BMI", cae: "356218657"},
{ fName: "Liz", mName: "", lName: "Constantine", suffix: "", pro: "BMI", cae: "238439646"},
{ fName: "Sharon", mName: "", lName: "Heintz", suffix: "", pro: "BMI", cae: "477211846"},
{ fName: "Bryan", mName: "Alexander", lName: "Moran", suffix: "", pro: "BMI", cae: "532621480"},
{ fName: "Greg", mName: "Gerard", lName: "Gerosky", suffix: "", pro: "BMI", cae: "540903276"},
{ fName: "Jim", mName: "", lName: "Taylor", suffix: "", pro: "BMI", cae: ""},
{ fName: "Mark", mName: "", lName: "Jackson", suffix: "", pro: "BMI", cae: ""},
{ fName: "Nicholas", mName: "A", lName: "Scott", suffix: "", pro: "BMI", cae: "538576610"},
{ fName: "Richard", mName: "Michael", lName: "Freeze", suffix: "", pro: "BMI", cae: "542274072"},
{ fName: "Robert", mName: "K", lName: "Williams", suffix: "Jr", pro: "BMI", cae: "487519310"},
{ fName: "Rocky", mName: "", lName: "Larson", suffix: "", pro: "BMI", cae: "401015730"},
{ fName: "Enoch", mName: "Lyndell", lName: "Harris", suffix: "", pro: "BMI", cae: "358151263"},
{ fName: "Christy", mName: "Sara", lName: "Carew", suffix: "", pro: "BMI", cae: "511755667"},
{ fName: "George", mName: "Bartholomew", lName: "Samolis", suffix: "Jr", pro: "BMI", cae: "356252267"},
{ fName: "David", mName: "", lName: "Wachs", suffix: "", pro: "BMI", cae: "452093960"},
{ fName: "Mike", mName: "David Max", lName: "Abdelmessih", suffix: "", pro: "BMI", cae: "515260973"},
{ fName: "Craig", mName: "Michael", lName: "Pilo", suffix: "", pro: "BMI", cae: "457333253"},
{ fName: "Robert", mName: "James", lName: "Conti", suffix: "", pro: "BMI", cae: "53131126"},
{ fName: "Daren", mName: "", lName: "Singletary", suffix: "", pro: "BMI", cae: "575717219"},
{ fName: "David", mName: "P", lName: "Keif", suffix: "", pro: "BMI", cae: "350764660"},
{ fName: "Ildar", mName: "", lName: "Kayupov", suffix: "", pro: "BMI", cae: "633837630"},
{ fName: "Zac", mName: "A", lName: "Cataldo", suffix: "", pro: "BMI", cae: "202739590"},
{ fName: "Russell", mName: "David", lName: "Kniffin", suffix: "", pro: "BMI", cae: "619531641"},
{ fName: "Brent", mName: "Scott", lName: "Godin", suffix: "", pro: "BMI", cae: "643420276"},
{ fName: "William", mName: "Frederick", lName: "Graettinger", suffix: "Jr", pro: "BMI", cae: "615455846"},
{ fName: "Damian", mName: "Michael Lamone", lName: "Williams", suffix: "", pro: "BMI", cae: "426358355"},
{ fName: "Daniel", mName: "Kurt", lName: "Radlauer", suffix: "", pro: "BMI", cae: "138945049"},
{ fName: "Brendan", mName: "H", lName: "Murphy", suffix: "", pro: "BMI", cae: "602599544"},
{ fName: "Terrence", mName: "Christopher", lName: "Town", suffix: "", pro: "BMI", cae: "665126247"},
{ fName: "Shane", mName: "", lName: "Murphy", suffix: "", pro: "BMI", cae: "550230711"},
{ fName: "Roy", mName: "", lName: "Campanella", suffix: "III", pro: "BMI", cae: "217781851"},
{ fName: "Sarah", mName: "Susan", lName: "Hethcoat", suffix: "", pro: "BMI", cae: "464630650"},
{ fName: "Eric", mName: "Carlson", lName: "Daubney", suffix: "", pro: "BMI", cae: "647907704"},
{ fName: "Michael", mName: "J", lName: "Bozzo", suffix: "Jr", pro: "BMI", cae: "531601396"},
{ fName: "Christopher", mName: "L", lName: "Williams", suffix: "", pro: "BMI", cae: "193859908"},
{ fName: "Matthew", mName: "Carl", lName: "Lore", suffix: "", pro: "BMI", cae: "594626215"},
{ fName: "David", mName: "S", lName: "Bateman", suffix: "", pro: "BMI", cae: "445203779"},
{ fName: "Robert", mName: "D", lName: "Sands", suffix: "Jr", pro: "BMI", cae: "216451000"},
{ fName: "Adam", mName: "Parry", lName: "Thomas", suffix: "", pro: "BMI", cae: "674670807"},
{ fName: "Kevin", mName: "", lName: "Techmeier", suffix: "", pro: "BMI", cae: "682276814"},
{ fName: "Jonathan", mName: "David", lName: "Bostrom", suffix: "", pro: "BMI", cae: "690247044"},
{ fName: "John", mName: "D", lName: "Willis", suffix: "", pro: "BMI", cae: "352199063"},
{ fName: "Ronald", mName: "J", lName: "Millar", suffix: "", pro: "BMI", cae: "697763866"},
{ fName: "Thomas", mName: "Per", lName: "Andersson", suffix: "", pro: "BMI", cae: "705498036"},
{ fName: "John", mName: "", lName: "Collis", suffix: "", pro: "BMI", cae: "703121896"},
{ fName: "Colin", mName: "Eliot", lName: "Schiller", suffix: "", pro: "BMI", cae: "603505880"},
{ fName: "Logan", mName: "Cole", lName: "Cookingham", suffix: "", pro: "BMI", cae: "706964813"},
{ fName: "Buddy", mName: "Richard", lName: "Nuanez", suffix: "", pro: "BMI", cae: "39202304"},
{ fName: "Sharon", mName: "Stark", lName: "Mayeux", suffix: "", pro: "BMI", cae: "714243962"},
{ fName: "Scott", mName: "Christian", lName: "Marzullo", suffix: "", pro: "BMI", cae: "487564403"},
{ fName: "Jacob", mName: "Whitney", lName: "Shea", suffix: "", pro: "BMI", cae: "750507947"},
{ fName: "Fin", mName: "T", lName: "Johnston", suffix: "", pro: "BMI", cae: "215992650"},
{ fName: "Gary", mName: "Lee", lName: "Melvin", suffix: "", pro: "BMI", cae: "422377374"},
{ fName: "Christopher", mName: "Ross", lName: "Kennedy", suffix: "", pro: "BMI", cae: "536950726"},
{ fName: "Charles", mName: "Henry Leyden", lName: "Sehres", suffix: "", pro: "BMI", cae: "671959990"},
{ fName: "David", mName: "D", lName: "Shuttleworth", suffix: "", pro: "BMI", cae: "726510851"},
{ fName: "Josef", mName: "", lName: "Peters", suffix: "", pro: "BMI", cae: "218677248"},
{ fName: "James", mName: "Aaron", lName: "Combs", suffix: "", pro: "BMI", cae: "229426170"},
{ fName: "Lane", mName: "Sean", lName: "Thomas", suffix: "", pro: "BMI", cae: "647947299"},
{ fName: "Donald", mName: "Vincent", lName: "Ferrone", suffix: "", pro: "BMI", cae: "533224191"},
{ fName: "William", mName: "Arthur", lName: "Keskey", suffix: "", pro: "BMI", cae: "752961125"},
{ fName: "Christopher", mName: "Peter", lName: "Cardena", suffix: "", pro: "BMI", cae: "495998367"},
{ fName: "Daniel", mName: "Weston", lName: "Meyer", suffix: "", pro: "BMI", cae: "642958613"},
{ fName: "Jeffrey", mName: "Mitchell", lName: "Andrews", suffix: "", pro: "BMI", cae: "237277848"},
{ fName: "Lewis", mName: "James", lName: "Gregory", suffix: "", pro: "BMI", cae: "185207175"},
{ fName: "Austin", mName: "Clifton", lName: "Mason", suffix: "", pro: "BMI", cae: "510710211"},
{ fName: "Josiel", mName: "", lName: "Perez", suffix: "", pro: "BMI", cae: "714149165"},
{ fName: "Victor", mName: "Joseph", lName: "Romine", suffix: "", pro: "BMI", cae: "765465309"},
{ fName: "Matthew", mName: "Francis", lName: "Basile", suffix: "", pro: "BMI", cae: "188917412"},
{ fName: "Paul", mName: "H", lName: "Glover", suffix: "", pro: "BMI", cae: "222447397"},
{ fName: "Matthew", mName: "Stephen", lName: "Rohde", suffix: "", pro: "BMI", cae: "179500654"},
{ fName: "Eric", mName: "A", lName: "Baines", suffix: "", pro: "BMI", cae: "353261872"},
{ fName: "Peter", mName: "Van Gordon", lName: "Banker", suffix: "", pro: "BMI", cae: "451074187"},
{ fName: "Michael", mName: "Thomas", lName: "Brown", suffix: "", pro: "BMI", cae: "616398232"},
{ fName: "Cagdas", mName: "", lName: "Donmezer", suffix: "", pro: "BMI", cae: "704896126"},
{ fName: "Hun", mName: "Min", lName: "Park", suffix: "", pro: "BMI", cae: "797334002"},
{ fName: "Erick", mName: "B", lName: "Gilbertson", suffix: "", pro: "BMI", cae: "186610362"},
{ fName: "Matthew", mName: "Michael", lName: "Allegre", suffix: "", pro: "BMI", cae: "668791679"},
{ fName: "Joshua", mName: "Patrick", lName: "Lopez", suffix: "", pro: "BMI", cae: "796788449"},
{ fName: "Andrew", mName: "James", lName: "Krause", suffix: "", pro: "BMI", cae: "733136660"},
{ fName: "John", mName: "Stewart", lName: "Burke", suffix: "", pro: "BMI", cae: "482701358"},
{ fName: "John", mName: "Martin", lName: "Camp", suffix: "", pro: "BMI", cae: "352064095"},
{ fName: "Sungtae", mName: "", lName: "Kim", suffix: "", pro: "BMI", cae: "591456231"},
{ fName: "Konstantinos", mName: "", lName: "Panagiotidis", suffix: "", pro: "BMI", cae: "705225181"},
{ fName: "Vance", mName: "K", lName: "Marino", suffix: "", pro: "BMI", cae: "486620138"},
{ fName: "Tracey", mName: "James", lName: "Marino", suffix: "", pro: "BMI", cae: "486620334"},
{ fName: "Martin", mName: "", lName: "Zitzelberger", suffix: "", pro: "BMI", cae: "795750099"},
{ fName: "Harold", mName: "Jonathan Krikor", lName: "Cragin", suffix: "", pro: "BMI", cae: "193106972"},
{ fName: "Phillip", mName: "Marc", lName: "Bosserman", suffix: "", pro: "BMI", cae: "358166538"},
{ fName: "Keith", mName: "Anthony", lName: "Sheppard", suffix: "", pro: "BMI", cae: "476708124"},
{ fName: "Panagiotis", mName: "", lName: "Katsivardakos", suffix: "", pro: "BMI", cae: "736826219"},
{ fName: "John", mName: "Alexander", lName: "Zych", suffix: "", pro: "BMI", cae: "458470529"},
{ fName: "Jason", mName: "Daniel", lName: "Bouma", suffix: "", pro: "BMI", cae: "533970442"},
{ fName: "Charles", mName: "Aaron", lName: "Bamford", suffix: "", pro: "BMI", cae: "518641352"},
{ fName: "Demetri", mName: "P", lName: "Larry", suffix: "", pro: "BMI", cae: "617519441"},
{ fName: "David", mName: "", lName: "Hollandsworth", suffix: "", pro: "BMI", cae: "673957592"},
{ fName: "Jesus", mName: "A", lName: "Velazquez", suffix: "", pro: "BMI", cae: "439949696"},
{ fName: "Richard", mName: "Michael", lName: "McCulley", suffix: "", pro: "BMI", cae: "355968902"},
{ fName: "Brandon", mName: "Thomas", lName: "Knight", suffix: "", pro: "BMI", cae: "816996979"},
{ fName: "Joseph", mName: "", lName: "Clar", suffix: "", pro: "BMI", cae: "594904704"},
{ fName: "John", mName: "Jeffrey", lName: "Pelsone", suffix: "", pro: "BMI", cae: "566735316"},
{ fName: "Mark", mName: "C", lName: "MacTaggart", suffix: "", pro: "BMI", cae: "608776809"},
{ fName: "Jordan", mName: "Tadashi", lName: "Kim", suffix: "", pro: "BMI", cae: "821391064"},
{ fName: "Joohyun", mName: "", lName: "Park", suffix: "", pro: "BMI", cae: "577913111"},
{ fName: "Jeremy", mName: "Jesse", lName: "Rowe", suffix: "", pro: "BMI", cae: "833397321"},
{ fName: "Steven", mName: "Dominic", lName: "Lucas", suffix: "", pro: "BMI", cae: "841630748"},
{ fName: "Brian", mName: "Michael", lName: "Fuller", suffix: "", pro: "BMI", cae: "843899188"},
{ fName: "Brian", mName: "Adam", lName: "Jefferson", suffix: "", pro: "BMI", cae: "673561427"},
{ fName: "Klaryssa", mName: "Nicole", lName: "Korol", suffix: "", pro: "BMI", cae: "544428548"},
{ fName: "Joshua", mName: "R", lName: "Harris", suffix: "", pro: "BMI", cae: "357418347"},
{ fName: "Harold", mName: "Webster", lName: "Griffin", suffix: "Sr", pro: "BMI", cae: "603581174"},
{ fName: "Kristina", mName: "Marie", lName: "Scheps", suffix: "", pro: "BMI", cae: "844539218"},
{ fName: "Tony", mName: "", lName: "Gilkyson", suffix: "", pro: "BMI", cae: "222976755"},
{ fName: "Daniel", mName: "", lName: "Glicken", suffix: "", pro: "BMI", cae: "481171856"},
{ fName: "Charles", mName: "W", lName: "Anderson", suffix: "", pro: "BMI", cae: "227822566"},
{ fName: "Joseph", mName: "Vincent", lName: "Carpenter", suffix: "", pro: "BMI", cae: "768914194"},
{ fName: "Taras", mName: "Ihor", lName: "Prodaniuk", suffix: "", pro: "BMI", cae: "243331401"},
{ fName: "Zachary", mName: "Thomas", lName: "Losacker", suffix: "", pro: "BMI", cae: "856938479"},
{ fName: "Kyle", mName: "Lynn", lName: "Sigmon", suffix: "", pro: "BMI", cae: "857410821"},
{ fName: "Ryan", mName: "Keith", lName: "Ricks", suffix: "", pro: "BMI", cae: "818142056"},
{ fName: "KC", mName: "", lName: "Carter", suffix: "", pro: "BMI", cae: "650845342"},
{ fName: "Aurel", mName: "D", lName: "Baker", suffix: "", pro: "BMI", cae: "664509330"},
{ fName: "Anthony", mName: "Donald", lName: "Martinez", suffix: "", pro: "BMI", cae: "667541810"},
{ fName: "Christopher", mName: "Jay", lName: "Asman", suffix: "", pro: "BMI", cae: "242545286"},
{ fName: "Kiyoshi", mName: "Alexander", lName: "Matsuyama", suffix: "", pro: "BMI", cae: "557769492"},
{ fName: "Lawrence", mName: "", lName: "Ricks", suffix: "", pro: "BMI", cae: "628812336"},
{ fName: "Brian", mName: "", lName: "Reid", suffix: "", pro: "BMI", cae: "542831949"},
{ fName: "John", mName: "W", lName: "Argosino", suffix: "", pro: "BMI", cae: "543505664"},
{ fName: "Haakon", mName: "", lName: "Graf", suffix: "", pro: "BMI", cae: "13190231"},
{ fName: "Kia", mName: "Lynn", lName: "Glover", suffix: "", pro: "BMI", cae: "612638069"},
{ fName: "J", mName: "Mario", lName: "Ramirez", suffix: "III", pro: "BMI", cae: "883229803"},
{ fName: "Ryan", mName: "Matthew", lName: "Lottes", suffix: "", pro: "BMI", cae: "629285715"},
{ fName: "Steve", mName: "", lName: "Conn", suffix: "", pro: "BMI", cae: "215302615"},
{ fName: "David", mName: "", lName: "Brozozowski", suffix: "", pro: "BMI", cae: "404971658"},
{ fName: "Philip", mName: "De Freeze", lName: "Brown", suffix: "", pro: "BMI", cae: "752818325"},
{ fName: "Jon", mName: "", lName: "Ong", suffix: "", pro: "BMI", cae: "659788761"},
{ fName: "Matthew", mName: "Raymond", lName: "Van Den Heuvel", suffix: "", pro: "BMI", cae: "755286315"},
{ fName: "Reginald", mName: "Garrick", lName: "Joseph", suffix: "", pro: "BMI", cae: "619660235"},
{ fName: "Jordan", mName: "", lName: "Costello", suffix: "", pro: "BMI", cae: "891910118"},
{ fName: "Anton", mName: "Aleksander", lName: "Fedorov", suffix: "", pro: "BMI", cae: "886110821"},
{ fName: "Stanley", mName: "", lName: "Jeong", suffix: "", pro: "BMI", cae: "730653654"},
{ fName: "Brandon", mName: "Rashod", lName: "Singleton", suffix: "", pro: "BMI", cae: "621879823"},
{ fName: "Brian", mName: "", lName: "Polar", suffix: "", pro: "BMI", cae: "673561525"},
{ fName: "Ricardo", mName: "", lName: "Balboa", suffix: "", pro: "BMI", cae: "553591045"},
{ fName: "Sheila", mName: "T", lName: "Brennan", suffix: "", pro: "BMI", cae: "467472424"},
{ fName: "Adam", mName: "David", lName: "Willard", suffix: "", pro: "BMI", cae: "187095241"},
{ fName: "Nathan", mName: "Allen", lName: "Myotte", suffix: "", pro: "BMI", cae: "807242554"},
{ fName: "Samuel", mName: "Bruce", lName: "Davis", suffix: "Jr.", pro: "BMI", cae: "833965015"},
{ fName: "Frank", mName: "", lName: "Schlimbach", suffix: "", pro: "BMI", cae: "362546947"},
{ fName: "David", mName: "", lName: "Forlano", suffix: "", pro: "BMI", cae: "755642029"},
{ fName: "Roberto", mName: "", lName: "Rodriguez Del Toro", suffix: "", pro: "BMI", cae: "846645996"},
{ fName: "Jamus", mName: "", lName: "Hayes", suffix: "", pro: "BMI", cae: "673654613"},
{ fName: "Anthony", mName: "", lName: "Sobers-Assue", suffix: "", pro: "BMI", cae: "542348851"},
{ fName: "Roderick", mName: "", lName: "Kelly", suffix: "", pro: "BMI", cae: "535586330"},
{ fName: "Gregory ", mName: "Duane", lName: "Goss", suffix: "", pro: "BMI", cae: "696972959"},
{ fName: "Chris", mName: "", lName: "Dauphin", suffix: "", pro: "BMI", cae: "545212770"},
{ fName: "Jacques", mName: "", lName:"Franko", suffix: "", pro: "BMI", cae: "775018333"},
{ fName: "Daniel", mName: "Alejandro", lName: "Fernandez", suffix: "", pro: "BMI", cae: "834639710"},
{ fName: "Denard", mName: "Cornell", lName: "Tanksley", suffix: "", pro: "BMI", cae: "601555088"},
{ fName: "Vashni", mName: "Lynsias", lName: "Matthews", suffix: "", pro: "BMI", cae: "658210449"},
{ fName: "Lloyd", mName: "Anthony", lName: "Jarvis", suffix: "", pro: "BMI", cae: "881909987"},
{ fName: "Richard", mName: "Michael", lName: "Freeze", suffix: "", pro: "BMI", cae: "542274072"},
{ fName: "Eugene", mName: "", lName: "Hargrow", suffix: "Jr", pro: "BMI", cae: "852105561"},
{ fName: "Gregory", mName: "Vance", lName: "Savage", suffix: "Jr", pro: "BMI", cae: "722571456"},
{ fName: "Kevin", mName: "James", lName: "Peacock", suffix: "", pro: "BMI", cae: "585992580"},
{ fName: "Charles ", mName: "Stanley", lName: "Edwards", suffix: "II", pro: "BMI", cae: "1012203446"},
{ fName: "Cornelius ", mName: "Leon", lName: "Coleman", suffix: "Jr", pro: "BMI", cae: "722066470"},
{ fName: "Jonathan ", mName: "David", lName: "Miles", suffix: "", pro: "BMI", cae: "846089998"},
{ fName: "Stephen", mName: "Eric", lName: "Means", suffix: "", pro: "BMI", cae: "361113305"},
{ fName: "Kevin ", mName: "Troy", lName: "Brightman", suffix: "", pro: "BMI", cae: "559443516"},
{ fName: "Hannsjoerg", mName: "", lName: "Scheid", suffix: "", pro: "BMI", cae: "140109131"},
{ fName: "Joshua", mName: "Russell", lName: "Hill", suffix: "", pro: "BMI", cae: "634080077"},
{ fName: "Rashiid", mName: "", lName: "Cummins", suffix: "", pro: "BMI", cae: "602392967"},
{ fName: "Josh ", mName: "Rai", lName: "Parra", suffix: "", pro: "BMI", cae: "853923415"},
{ fName: "Matt", mName: "", lName: "Bolton", suffix: "", pro: "BMI", cae: "853927207"},
{ fName: "Ravi", mName: "Krishna", lName: "Nidamarthy", suffix: "", pro: "BMI", cae: "1022503522"},
{ fName: "Ralph", mName: "Stanley", lName: "Oleski", suffix: "", pro: "BMI", cae: "185572833"},
{ fName: "Walter", mName: "", lName: "Bowie", suffix: "III", pro: "BMI", cae: "862995971"},
{ fName: "Ryan", mName: "David", lName: "Hanifl", suffix: "", pro: "ASCAP", cae: "428132379"},
{ fName: "Alberto", mName: "", lName: "Morello", suffix: "", pro: "ASCAP", cae: "261155980"},
{ fName: "Brett", mName: "Lyttle", lName: "Cookingham", suffix: "", pro: "ASCAP", cae: "338404077"},
{ fName: "Daniel", mName: "E", lName: "Stein", suffix: "", pro: "ASCAP", cae: "126694458"},
{ fName: "Derek", mName: "De Witt", lName: "Luff", suffix: "", pro: "ASCAP", cae: "128754751"},
{ fName: "Mark", mName: "C", lName: "Cross", suffix: "", pro: "ASCAP", cae: "334935747"},
{ fName: "Robin", mName: "C", lName: "DiMaggio", suffix: "", pro: "ASCAP", cae: "598507201"},
{ fName: "Timothy", mName: "W", lName: "Isle", suffix: "", pro: "ASCAP", cae: "339186734"},
{ fName: "Andre", mName: "O", lName: "Mayeux", suffix: "", pro: "ASCAP", cae: "127794447"},
{ fName: "Greg", mName: "", lName: "Clewley", suffix: "", pro: "ASCAP", cae: "128368265"},
{ fName: "Ian", mName: "", lName: "Herzon", suffix: "", pro: "ASCAP", cae: "480728145"},
{ fName: "John", mName: "", lName: "Chamberlin", suffix: "", pro: "ASCAP", cae: "421494768"},
{ fName: "John", mName: "Sherman", lName: "Morris", suffix: "", pro: "ASCAP", cae: "342870560"},
{ fName: "Johnny", mName: "", lName: "Baker", suffix: "", pro: "ASCAP", cae: "426959322"},
{ fName: "Marc", mName: "Duane", lName: "Pattison", suffix: "", pro: "ASCAP", cae: "344693149"},
{ fName: "Michael", mName: "G", lName: "Shapiro", suffix: "", pro: "ASCAP", cae: "340762183"},
{ fName: "Miriam", mName: "A", lName: "Mayer", suffix: "", pro: "ASCAP", cae: "127551972"},
{ fName: "Nard", mName: "", lName: "Berings", suffix: "", pro: "ASCAP", cae: "221301145"},
{ fName: "Ravi", mName: "", lName: "Jakhotia", suffix: "", pro: "ASCAP", cae: "432306200"},
{ fName: "Burleigh", mName: "Girasole", lName: "Drummond", suffix: "", pro: "ASCAP", cae: "125419687"},
{ fName: "Gregory", mName: "A", lName: "Sankovich", suffix: "", pro: "ASCAP", cae: "346015683"},
{ fName: "William", mName: "Harrison", lName: "Meyle", suffix: "", pro: "ASCAP", cae: "452300990"},
{ fName: "Gordon", mName: "Ian", lName: "Riddell", suffix: "", pro: "ASCAP", cae: "514869236"},
{ fName: "John", mName: "Theodore", lName: "Aquino", suffix: "", pro: "ASCAP", cae: "471952240"},
{ fName: "Jonathan", mName: "Patrick", lName: "Merkel", suffix: "", pro: "ASCAP", cae: "485541138"},
{ fName: "Joy", mName: "Angshu", lName: "Basu", suffix: "", pro: "ASCAP", cae: "338943137"},
{ fName: "Kevin", mName: "P", lName: "McDaniels", suffix: "", pro: "ASCAP", cae: "342074490"},
{ fName: "Nancy", mName: "Jane", lName: "Kho", suffix: "", pro: "ASCAP", cae: "344018686"},
{ fName: "Steven", mName: "Scott", lName: "Rosenblum", suffix: "", pro: "ASCAP", cae: "348802448"},
{ fName: "Paul", mName: "Michael", lName: "Karpinski", suffix: "", pro: "ASCAP", cae: "456608535"},
{ fName: "Wayne", mName: "Allen", lName: "Boyer", suffix: "", pro: "ASCAP", cae: "127694158"},
{ fName: "Delmar", mName: "Ervin", lName: "Brown", suffix: "", pro: "ASCAP", cae: "58404969"},
{ fName: "Brice", mName: "Harrison", lName: "Martin", suffix: "", pro: "ASCAP", cae: "337566734"},
{ fName: "David", mName: "Lee", lName: "Patt", suffix: "", pro: "ASCAP", cae: "51954868"},
{ fName: "Hussain", mName: "F", lName: "Jiffry", suffix: "", pro: "ASCAP", cae: "337244959"},
{ fName: "Michelle", mName: "Elisabeth", lName: "Geier", suffix: "", pro: "ASCAP", cae: "454982322"},
{ fName: "Shahar", mName: "", lName: "Tabachnik", suffix: "", pro: "ASCAP", cae: "419826827"},
{ fName: "Michael", mName: "L", lName: "Clinco", suffix: "", pro: "ASCAP", cae: "129608954"},
{ fName: "Todd", mName: "", lName: "Dutkevitch", suffix: "", pro: "ASCAP", cae: "436971919"},
{ fName: "Richard", mName: "", lName: "Gelles", suffix: "", pro: "ASCAP", cae: "422054994"},
{ fName: "Benjamin", mName: "Nils", lName: "Kopec", suffix: "", pro: "ASCAP", cae: "480292552"},
{ fName: "Matt", mName: "T", lName: "Gruber", suffix: "", pro: "ASCAP", cae: "402796951"},
{ fName: "Erika", mName: "", lName: "Lieberman", suffix: "", pro: "ASCAP", cae: "413686457"},
{ fName: "Michael", mName: "Louis", lName: "Robinson", suffix: "", pro: "ASCAP", cae: "517181367"},
{ fName: "Kevin", mName: "Darnell", lName: "Barnes", suffix: "", pro: "ASCAP", cae: "468472516"},
{ fName: "Daniel", mName: "Scott", lName: "Hoock", suffix: "", pro: "ASCAP", cae: "575328820"},
{ fName: "Dennis", mName: "Alan", lName: "Earnest", suffix: "", pro: "ASCAP", cae: "207995440"},
{ fName: "Nick", mName: "", lName: "Ammons", suffix: "", pro: "ASCAP", cae: "606954727"},
{ fName: "Keith", mName: "S", lName: "Kohn", suffix: "", pro: "ASCAP", cae: "342195180"},
{ fName: "Jason", mName: "Scott", lName: "Mandell", suffix: "", pro: "ASCAP", cae: "417635652"},
{ fName: "Christopher", mName: "Robert", lName: "Smith", suffix: "", pro: "ASCAP", cae: "341137498"},
{ fName: "Austin", mName: "Edward", lName: "Poulain", suffix: "", pro: "ASCAP", cae: "623674542"},
{ fName: "Zachary", mName: "Scott", lName: "McIntyre", suffix: "", pro: "ASCAP", cae: "552184752"},
{ fName: "Scott", mName: "D", lName: "Card", suffix: "", pro: "ASCAP", cae: "618359919"},
{ fName: "Kennon", mName: "Marwin", lName: "Ward", suffix: "", pro: "ASCAP", cae: "611743669"},
{ fName: "Mark", mName: "S", lName: "Hollingsworth", suffix: "", pro: "ASCAP", cae: "349658120"},
{ fName: "Renzo", mName: "", lName: "Miralles", suffix: "", pro: "ASCAP", cae: "615542854"},
{ fName: "Henry", mName: "Stifel", lName: "Whitaker", suffix: "", pro: "ASCAP", cae: "665112557"},
{ fName: "Jude", mName: "", lName: "Gold", suffix: "", pro: "ASCAP", cae: "634763629"},
{ fName: "Darnell", mName: "Bernard", lName: "Beasley", suffix: "", pro: "ASCAP", cae: "551025588"},
{ fName: "Sammie", mName: "B", lName: "Rogers", suffix: "", pro: "ASCAP", cae: "684317524"},
{ fName: "Rolando", mName: "N", lName: "Vega", suffix: "", pro: "ASCAP", cae: "337934928"},
{ fName: "James", mName: "Raymond", lName: "Strohmeier", suffix: "", pro: "ASCAP", cae: "697654872"},
{ fName: "Jonathan", mName: "Matthew", lName: "Howard", suffix: "", pro: "ASCAP", cae: "528223563"},
{ fName: "Nathan", mName: "Scott", lName: "Bowen", suffix: "", pro: "ASCAP", cae: "567986672"},
{ fName: "Marc", mName: "", lName: "Aramian", suffix: "", pro: "ASCAP", cae: "73887434"},
{ fName: "Justin", mName: "", lName: "Andres", suffix: "", pro: "ASCAP", cae: "513319973"},
{ fName: "Robert", mName: "Wayne", lName: "Johnson", suffix: "", pro: "ASCAP", cae: "349267531"},
{ fName: "Kevin", mName: "", lName: "McNally", suffix: "", pro: "ASCAP", cae: "572945809"},
{ fName: "James", mName: "Arohade", lName: "Winters", suffix: "", pro: "ASCAP", cae: "723167652"},
{ fName: "James", mName: "R", lName: "Henken", suffix: "", pro: "ASCAP", cae: "337656831"},
{ fName: "Leslie", mName: "Ann", lName: "Spiro", suffix: "", pro: "ASCAP", cae: "125999826"},
{ fName: "Jamie", mName: "", lName: "Wollam", suffix: "", pro: "ASCAP", cae: "511580484"},
{ fName: "I", mName: "Robert", lName: "Bernstein", suffix: "", pro: "ASCAP", cae: "334560084"},
{ fName: "Eric", mName: "Victor", lName: "Bolvin", suffix: "", pro: "ASCAP", cae: "125281004"},
{ fName: "Evan", mName: "James", lName: "Bernardin", suffix: "", pro: "ASCAP", cae: "714922546"},
{ fName: "Steven", mName: "Robert", lName: "Wilkinson", suffix: "", pro: "ASCAP", cae: "340596659"},
{ fName: "Devin", mName: "Martin", lName: "Farney", suffix: "", pro: "ASCAP", cae: "675190524"},
{ fName: "Reymundo", mName: "", lName: "Garcia", suffix: "", pro: "ASCAP", cae: "712908058"},
{ fName: "Trygge", mName: "Olaf", lName: "Toven", suffix: "", pro: "ASCAP", cae: "727018748"},
{ fName: "John", mName: "Francis", lName: "Ryan", suffix: "", pro: "ASCAP", cae: "674832905"},
{ fName: "Jared", mName: "Phillip", lName: "Scott", suffix: "", pro: "ASCAP", cae: "595067612"},
{ fName: "Ryan", mName: "David", lName: "Leyva", suffix: "", pro: "ASCAP", cae: "533359747"},
{ fName: "Willie", mName: "", lName: "Aron", suffix: "", pro: "ASCAP", cae: "205465195"},
{ fName: "Zachary", mName: "A", lName: "Schaffer", suffix: "", pro: "ASCAP", cae: "409907834"},
{ fName: "Matthew", mName: "Paul", lName: "Baumbach", suffix: "", pro: "ASCAP", cae: "526626154"},
{ fName: "Nikolaos", mName: "", lName: "Makaris", suffix: "", pro: "ASCAP", cae: "749018232"},
{ fName: "Craig", mName: "F", lName: "Seganti", suffix: "", pro: "ASCAP", cae: "339589117"},
{ fName: "Robert", mName: "Thompson", lName: "Brandes", suffix: "", pro: "ASCAP", cae: "751007476"},
{ fName: "Ryan", mName: "C", lName: "Collins", suffix: "", pro: "ASCAP", cae: "406120314"},
{ fName: "James", mName: "Evan", lName: "Doyle", suffix: "", pro: "ASCAP", cae: "533767925"},
{ fName: "Mychael", mName: "Motoki", lName: "Kinoshita", suffix: "", pro: "ASCAP", cae: "665396307"},
{ fName: "Jason", mName: "Phillip", lName: "Dzamba", suffix: "", pro: "ASCAP", cae: "585282322"},
{ fName: "Johnny", mName: "", lName: "Moore", suffix: "", pro: "ASCAP", cae: "692029534"},
{ fName: "Angus", mName: "", lName: "Underhill", suffix: "", pro: "ASCAP", cae: "778574771"},
{ fName: "Jessica", mName: "Marie", lName: "Mellott", suffix: "", pro: "ASCAP", cae: "492134066"},
{ fName: "Evan", mName: "Lawrence", lName: "Eder", suffix: "", pro: "ASCAP", cae: "342027008"},
{ fName: "Xavier", mName: "Jean", lName: "Nathan", suffix: "", pro: "ASCAP", cae: "738653410"},
{ fName: "Barbara", mName: "J", lName: "Weber", suffix: "", pro: "ASCAP", cae: "575897577"},
{ fName: "Isaac", mName: "", lName: "Moore", suffix: "", pro: "ASCAP", cae: "348430266"},
{ fName: "Peter", mName: "James", lName: "Maloney", suffix: "", pro: "ASCAP", cae: "343921958"},
{ fName: "David", mName: "Michael", lName: "Volmer", suffix: "", pro: "ASCAP", cae: "741855135"},
{ fName: "Johnny", mName: "W", lName: "Scering", suffix: "", pro: "ASCAP", cae: "346476440"},
{ fName: "Soyeun", mName: "", lName: "Lee", suffix: "", pro: "ASCAP", cae: "724045763"},
{ fName: "Cheyenne", mName: "Keoni", lName: "Boynton", suffix: "", pro: "ASCAP", cae: "348529630"},
{ fName: "Anthony", mName: "Jerome", lName: "Bowman", suffix: "", pro: "ASCAP", cae: "588104825"},
{ fName: "James", mName: "Richard", lName: "Niebergall", suffix: "", pro: "ASCAP", cae: "770982602"},
{ fName: "Thomas", mName: "J", lName: "O Connell", suffix: "", pro: "ASCAP", cae: "127681269"},
{ fName: "Solomon", mName: "Wesley", lName: "Ray", suffix: "", pro: "ASCAP", cae: "648806020"},
{ fName: "Chris", mName: "Alan", lName: "Maines", suffix: "", pro: "ASCAP", cae: "799957730"},
{ fName: "Michael", mName: "Aaron", lName: "Dishner", suffix: "", pro: "ASCAP", cae: "804725644"},
{ fName: "Eric", mName: "Matthew", lName: "Anderson", suffix: "", pro: "ASCAP", cae: "564255639"},
{ fName: "Nicolas", mName: "Jonathan", lName: "Gomez", suffix: "", pro: "ASCAP", cae: "484676014"},
{ fName: "Jeff", mName: "B", lName: "Fishman", suffix: "", pro: "ASCAP", cae: "128740277"},
{ fName: "Emery", mName: "A", lName: "Hosley", suffix: "", pro: "ASCAP", cae: "341157490"},
{ fName: "Nathan", mName: "", lName: "Efstation", suffix: "", pro: "ASCAP", cae: "719627418"},
{ fName: "Nicholas", mName: "Joseph", lName: "Rodriguez", suffix: "", pro: "ASCAP", cae: "777375392"},
{ fName: "Kanoa", mName: "", lName: "Wolfe-Doblin", suffix: "", pro: "ASCAP", cae: "779427291"},
{ fName: "Michael", mName: "Joseph", lName: "Elias", suffix: "", pro: "ASCAP", cae: "801187564"},
{ fName: "Takeshi", mName: "", lName: "Seo", suffix: "", pro: "ASCAP", cae: "671171847"},
{ fName: "Anthony", mName: "George", lName: "Balaskas", suffix: "", pro: "ASCAP", cae: "508596525"},
{ fName: "Matthew", mName: "Roy", lName: "Ferree", suffix: "", pro: "ASCAP", cae: "820357460"},
{ fName: "Devin", mName: "Stepan", lName: "Norris", suffix: "", pro: "ASCAP", cae: "760961620"},
{ fName: "Pamela", mName: "Lois", lName: "Wahlberg", suffix: "", pro: "ASCAP", cae: "833179137"},
{ fName: "Haavard", mName: "Christopher", lName: "Hana", suffix: "", pro: "ASCAP", cae: "400421528"},
{ fName: "Shakir", mName: "Tesfa", lName: "Merraro", suffix: "", pro: "ASCAP", cae: "478968865"},
{ fName: "Jeffery", mName: "Todd", lName: "Edwards", suffix: "", pro: "ASCAP", cae: "348259339"},
{ fName: "Donat", mName: "Konstantinovich", lName: "Kazarinoff", suffix: "", pro: "ASCAP", cae: "609451253"},
{ fName: "Dean", mName: "M", lName: "DiMarzo", suffix: "", pro: "ASCAP", cae: "748182125"},
{ fName: "Salvador", mName: "", lName: "Huerta", suffix: "", pro: "ASCAP", cae: "771552530"},
{ fName: "Trevor", mName: "", lName: "Hicks", suffix: "", pro: "ASCAP", cae: "838477297"},
{ fName: "Michael", mName: "John", lName: "Kurtin", suffix: "", pro: "ASCAP", cae: "575330154"},
{ fName: "Aaron", mName: "Alexander", lName: "Weits", suffix: "", pro: "ASCAP", cae: "842956998"},
{ fName: "Todd", mName: "Eric", lName: "Herfindal", suffix: "", pro: "ASCAP", cae: "337515169"},
{ fName: "Andrew", mName: "Paul", lName: "Griffin", suffix: "", pro: "ASCAP", cae: "346543946"},
{ fName: "Suzanne", mName: "Marie", lName: "Schnite", suffix: "", pro: "ASCAP", cae: "675714710"},
{ fName: "Richard", mName: "H", lName: "Martens", suffix: "", pro: "ASCAP", cae: "765017637"},
{ fName: "William", mName: "B", lName: "Bongiovanni", suffix: "", pro: "ASCAP", cae: "753336048"},
{ fName: "Richard", mName: "Alan", lName: "Dembowski", suffix: "", pro: "ASCAP", cae: "576625808"},
{ fName: "Sarah", mName: "Anne", lName: "Stanley", suffix: "", pro: "ASCAP", cae: "349307256"},
{ fName: "Jacqueline", mName: "", lName: "Van Bierk", suffix: "", pro: "ASCAP", cae: "341283681"},
{ fName: "Lisa", mName: "", lName: "Morris", suffix: "", pro: "ASCAP", cae: "850161169"},
{ fName: "Andrew", mName: "Joseph Paul", lName: "Smith", suffix: "", pro: "ASCAP", cae: "779769548"},
{ fName: "Andrew", mName: "Kenneth", lName: "James", suffix: "", pro: "ASCAP", cae: "796114614"},
{ fName: "Eddie", mName: "Abraham", lName: "Grey", suffix: "", pro: "ASCAP", cae: "716903245"},
{ fName: "Kevin", mName: "David", lName: "Comden", suffix: "", pro: "ASCAP", cae: "612638069"},
{ fName: "DeRon", mName: "M", lName: "Talley", suffix: "", pro: "ASCAP", cae: "511617780"},
{ fName: "Bill", mName: "", lName: "Snill", suffix: "", pro: "ASCAP", cae: "886350305"},
{ fName: "Joe", mName: "", lName: "Faraci", suffix: "", pro: "ASCAP", cae: "429408156"},
{ fName: "Donal", mName: "Christopher", lName: "McAuliffe", suffix: "", pro: "ASCAP", cae: "556836413"},
{ fName: "Christopher", mName: "Robert", lName: "Brown", suffix: "", pro: "ASCAP", cae: "456944516"},
{ fName: "Stephen", mName: "John", lName: "Spicer", suffix: "", pro: "ASCAP", cae: "565664220"},
{ fName: "David", mName: "Scott", lName: "Rockower", suffix: "", pro: "ASCAP", cae: "473664135"},
{ fName: "Jamel", mName: "C", lName: "Matias", suffix: "", pro: "ASCAP", cae: "796540597"},
{ fName: "Luke", mName: "Alexander", lName: "Shrestha", suffix: "", pro: "ASCAP", cae: "739399878"},
{ fName: "Paul", mName: "", lName: "Gelsomine", suffix: "", pro: "ASCAP", cae: "259775019"},
{ fName: "David", mName: "Earl", lName: "Christensen", suffix: "", pro: "ASCAP", cae: "509207763"},
{ fName: "Jeremy", mName: "Micklish", lName: "Barr", suffix: "", pro: "ASCAP", cae: "873022841"},
{ fName: "Vincent", mName: "Anthony", lName: "Muscarrella", suffix: "", pro: "ASCAP", cae: "369899374"},
{ fName: "Larry", mName: "Manigo", lName: "Talley", suffix: "", pro: "ASCAP", cae: "406851953"},
{ fName: "Alexander", mName: "James Greig", lName: "Stewart", suffix: "", pro: "ASCAP", cae: "889698823"},
{ fName: "Damarius", mName: "Lee", lName: "Watts", suffix: "", pro: "ASCAP", cae: "792206925"},
{ fName: "Ahmad", mName: "Mustafa", lName: "Alnoor", suffix: "", pro: "ASCAP", cae: "808150751"},
{ fName: "Andrew", mName: "Michael", lName: "Pertes", suffix: "", pro: "ASCAP", cae: "764118047"},
{ fName: "Angie", mName: "", lName: "Dais", suffix: "", pro: "ASCAP", cae: "825312461"},
{ fName: "Robert", mName: "", lName: "Lucas", suffix: "", pro: "ASCAP", cae: "378538804"},
{ fName: "Christopher", mName: "Levi", lName: "Joseph", suffix: "", pro: "ASCAP", cae: "387735410"},
{ fName: "David", mName: "", lName: "Ben-Porat", suffix: "", pro: "ASCAP", cae: "494088223"},
{ fName: "Amzi ", mName: "", lName: "Jackson", suffix: "", pro: "ASCAP", cae: "569133922"},
{ fName: "Gregory ", mName: "", lName: "Clewley", suffix: "", pro: "ASCAP", cae: "128368265"},
{ fName: "Kevin", mName: "Darnell", lName: "Barnes", suffix: "Jr", pro: "ASCAP", cae: "468472516"},
{ fName: "Andre", mName: "K", lName: "Herring", suffix: "", pro: "ASCAP", cae: "870293916"},
{ fName: "Edward", mName: "", lName: "Perez", suffix: "", pro: "ASCAP", cae: "619704242"},
{ fName: "Christopher", mName: "Dale", lName: "Chrisman", suffix: "", pro: "ASCAP", cae: "826271145"},
{ fName: "Willie", mName: "", lName: "Eaglin", suffix: "", pro: "ASCAP", cae: "460689627"},
{ fName: "Byron", mName: "", lName: "McConnell", suffix: "", pro: "ASCAP", cae: "470005988"},
{ fName: "Blake", mName: "Alan", lName: "Earnhart", suffix: "", pro: "ASCAP", cae: "855038135"},
{ fName: "Aren", mName: "G", lName: "Olsen", suffix: "", pro: "ASCAP", cae: "345512281"},
{ fName: "Joel", mName: "Anthony", lName: "Smith", suffix: "", pro: "ASCAP", cae: "849859070"},
{ fName: "Luke", mName: "Alexander", lName: "Shrestha", suffix: "", pro: "ASCAP", cae: "739399878"},
{ fName: "Simon", mName: "Hyung-Joo", lName: "Jay", suffix: "", pro: "ASCAP", cae: "746494406"},
{ fName: "Sean", mName: "Sama", lName: "Babila", suffix: "", pro: "ASCAP", cae: "898113894"},
{ fName: "Michael", mName: "R", lName: "Johnson", suffix: "", pro: "ASCAP", cae: "1001314937"},
{ fName: "Timothy", mName: "A", lName: "Byrd", suffix: "", pro: "ASCAP", cae: "339761335"},
{ fName: "Ramfis", mName: "Javier Rivera", lName: "Riviel", suffix: "", pro: "ASCAP", cae: "1003766294"},
{ fName: "Seth", mName: "A", lName: "Haynes", suffix: "", pro: "ASCAP", cae: "826244050"},
{ fName: "Kongcheng", mName: "", lName: "Her", suffix: "", pro: "ASCAP", cae: "868366974"},
{ fName: "Stephon", mName: "Delante", lName: "Manuel", suffix: "", pro: "ASCAP", cae: "608647725"},
{ fName: "Gregory ", mName: "Antoine", lName: "Clark", suffix: "", pro: "ASCAP", cae: "583854114"},
{ fName: "Reginald", mName: "Tobias Savage", lName: "Woods", suffix: "", pro: "ASCAP", cae: "776933782"},
{ fName: "Liridon", mName: "", lName: "Ademi", suffix: "", pro: "ASCAP", cae: "383564925"},
{ fName: "Darius", mName: "", lName: "Horton", suffix: "", pro: "ASCAP", cae: "1015251708"},
{ fName: "Mark", mName: "", lName: "Golden", suffix: "", pro: "ASCAP", cae: "793369198"},
{ fName: "Vahan", mName: "John", lName: "Aslanyan", suffix: "", pro: "ASCAP", cae: "745826708"},
{ fName: "Anthony", mName: "Ian Michael", lName: "Glynne", suffix: "", pro: "PRS", cae: "46867445"},
{ fName: "Grant", mName: "Warren", lName: "Ransom", suffix: "", pro: "PRS", cae: "256605364"},
{ fName: "Paul", mName: "John", lName: "Fairey", suffix: "", pro: "PRS", cae: "268565522"},
{ fName: "John", mName: "James", lName: "Godfrey", suffix: "", pro: "PRS", cae: "532226289"},
{ fName: "Matthew", mName: "De Bracey", lName: "Backer", suffix: "", pro: "PRS", cae: "268925910"},
{ fName: "Joseph", mName: "Paganini", lName: "Grant", suffix: "", pro: "PRS", cae: "295236837"},
{ fName: "Timothy", mName: "Michael", lName: "Ellis", suffix: "", pro: "PRS", cae: "265515756"},
{ fName: "Christopher", mName: "Patrick", lName: "Mahony", suffix: "", pro: "PRS", cae: "604558551"},
{ fName: "Mark", mName: "Christopher", lName: "Lee", suffix: "", pro: "PRS", cae: "469557697"},
{ fName: "Simrin", mName: "", lName: "Phull", suffix: "", pro: "PRS", cae: "719734320"},
{ fName: "James", mName: "Donald", lName: "Davies", suffix: "", pro: "PRS", cae: "290881832"},
{ fName: "James", mName: "Robert", lName: "Nisbet", suffix: "", pro: "PRS", cae: "508408658"},
{ fName: "Jorden", mName: "", lName: "Milnes", suffix: "", pro: "PRS", cae: "441324787"},
{ fName: "Steven", mName: "Richard", lName: "Bodsworth", suffix: "", pro: "PRS", cae: "555781419"},
{ fName: "Pranay", mName: "", lName: "Chand", suffix: "", pro: "PRS", cae: "782473511"},
{ fName: "Joyce", mName: "Camille", lName: "Kettering", suffix: "", pro: "PRS", cae: "706078156"},
{ fName: "Simon", mName: "", lName: "Iqbal", suffix: "", pro: "PRS", cae: "816560928"},
{ fName: "Garry", mName: "Donald William", lName: "Judd", suffix: "", pro: "PRS", cae: "85116285"},
{ fName: "Alexander", mName: "", lName: "Avramenko", suffix: "", pro: "PRS", cae: "832511465"},
{ fName: "Matthew", mName: "David", lName: "Sibley", suffix: "", pro: "PRS", cae: "643776125"},
{ fName: "Michail", mName: "Botzaropoulos", lName: "Votzaropoulos", suffix: "", pro: "PRS", cae: "756468794"},
{ fName: "Calum", mName: "Christopher", lName: "Upton", suffix: "", pro: "PRS", cae: "624038570"},
{ fName: "Patrick", mName: "", lName: "Yeboah", suffix: "", pro: "PRS", cae: "759669077"},
{ fName: "Sung", mName: "Jin", lName: "Cho", suffix: "", pro: "PRS", cae: "858553592"},
{ fName: "Yu", mName: "", lName: "Namikoshi", suffix: "", pro: "PRS", cae: "732340278"},
{ fName: "Corin", mName: "", lName: "Buckeridge", suffix: "", pro: "PRS", cae: "162506783"},
{ fName: "Ryan", mName: "", lName: "Trebilcock", suffix: "", pro: "PRS", cae: "869040712"},
{ fName: "John", mName: "Idris", lName: "Jones", suffix: "", pro: "SOCAN", cae: "38385855"},
{ fName: "Dion", mName: "Chesley", lName: "Tilley", suffix: "", pro: "SOCAN", cae: "251048987"},
{ fName: "Craig", mName: "Donald", lName: "Ducommun", suffix: "", pro: "SOCAN", cae: "223223516"},
{ fName: "Victoria", mName: "L", lName: "Flawith", suffix: "", pro: "SOCAN", cae: "474171845"},
{ fName: "Hugo", mName: "", lName: "McLaughlin", suffix: "", pro: "SOCAN", cae: "296552820"},
{ fName: "Patrick", mName: "", lName: "Francis", suffix: "", pro: "SOCAN", cae: "816794600"},
{ fName: "Andres", mName: "", lName: "Galarza", suffix: "", pro: "SOCAN", cae: "389709989"},
{ fName: "Christian", mName: "", lName: "Stonehhouse", suffix: "", pro: "SOCAN", cae: "423099271"},
{ fName: "Lloyd", mName: "Kevin", lName: "Shaw", suffix: "", pro: "SOCAN", cae: "6862350"},
{ fName: "Anthony", mName: "", lName: "Caligagan", suffix: "", pro: "SACEM", cae: "406297753"},
{ fName: "Axel", mName: "", lName: "Bay", suffix: "", pro: "SACEM", cae: "602116997"},
{ fName: "Olivia", mName: "", lName: "Le Sidaner", suffix: "", pro: "SACEM", cae: "794971182"},
{ fName: "Henrik", mName: "Sven", lName: "Zelizi", suffix: "", pro: "SUISA", cae: "439269818"},
{ fName: "Mariano", mName: "", lName: "Di Monte", suffix: "", pro: "SIAE", cae: "420849661"},
{ fName: "Marco", mName: "", lName: "Zaghi", suffix: "", pro: "SIAE", cae: "445596621"},
{ fName: "Silvio", mName: "D'Amico", lName: "Morais", suffix: "", pro: "SIAE", cae: "184312089"},
{ fName: "Riccardo", mName: "", lName: "Gibertini", suffix: "", pro: "SIAE", cae: "445596523"},
{ fName: "Antonio", mName: "", lName: "Vezzano", suffix: "", pro: "SIAE", cae: "430571681"},
{ fName: "Pietro", mName: "", lName: "Comite", suffix: "", pro: "SIAE", cae: "420827773"},
{ fName: "Angelo", mName: "", lName: "Cattoni", suffix: "", pro: "SIAE", cae: "437106084"},
{ fName: "Pietro", mName: "", lName: "Bonelli", suffix: "", pro: "SIAE", cae: "198657208"},
{ fName: "Christian", mName: "", lName: "Baghino", suffix: "", pro: "SIAE", cae: "437106182"},
{ fName: "Nino", mName: "", lName: "Maggioni", suffix: "", pro: "SIAE", cae: "506221399"},
{ fName: "Emanuel", mName: "", lName: "Bisquola", suffix: "", pro: "SIAE", cae: "711242591"},
{ fName: "Fabio", mName: "", lName: "Zonza", suffix: "", pro: "SIAE", cae: "459698092"},
{ fName: "Alberto", mName: "", lName: "Bonato", suffix: "", pro: "SIAE", cae: "453517949"},
{ fName: "Ruben", mName: "", lName: "Minuto", suffix: "", pro: "SIAE", cae: "468764303"},
{ fName: "Ermanno", mName: "", lName: "Fabbri", suffix: "", pro: "SIAE", cae: "180402"},
{ fName: "Daniele", mName: "", lName: "Rossi", suffix: "", pro: "SIAE", cae: "420952379"},
{ fName: "Cristiano", mName: "", lName: "Ferracuti", suffix: "", pro: "SIAE", cae: "427191070"},
{ fName: "Andreas", mName: "John Kenneth", lName: "Edmark", suffix: "", pro: "STIM", cae: "777054611"},
{ fName: "Shawn", mName: "", lName: "Pennington", suffix: "", pro: "SESAC", cae: "567210946"},
{ fName: "Arthur", mName: "Lee", lName: "Darien", suffix: "IV", pro: "SESAC", cae: "541491265"},
{ fName: "Abbas", mName: "Ali", lName: "Premjee", suffix: "", pro: "SESAC", cae: "572363837"},
{ fName: "Stephen", mName: "Scott", lName: "Booke", suffix: "", pro: "SESAC", cae: "197792995"},
{ fName: "Abbas", mName: "Ali", lName: "Premjee", suffix: "", pro: "SESAC", cae: "572363837"},
{ fName: "Ryan", mName: "Allen", lName: "Yerdon", suffix: "", pro: "SESAC", cae: "337917731"},
{ fName: "Omar", mName: "Saja", lName: "Medard", suffix: "", pro: "SESAC", cae: "570458441"},
{ fName: "Erick", mName: "Daniel", lName: "Eiser", suffix: "", pro: "SESAC", cae: "551921359"},
{ fName: "Mason", mName: "Wyrick", lName: "Ingram", suffix: "", pro: "SESAC", cae: "674728014"},
{ fName: "Charles", mName: "Avery", lName: "Stites", suffix: "", pro: "SESAC", cae: "506914947"},
{ fName: "Simon", mName: "Hyung-Joo", lName: "Jay", suffix: "", pro: "SESAC", cae: "746494406"},
{ fName: "Raphael", mName: "C", lName: "Fisher", suffix: "Jr", pro: "SESAC", cae: "189591902"},
{ fName: "Takashi", mName: "", lName: "Watanabe", suffix: "", pro: "JASRAC", cae: "613929245"},
{ fName: "Adrian", mName: "", lName: "Sood", suffix: "", pro: "IMRO", cae: "545394335"},
{ fName: "Adrian", mName: "", lName: "Sood", suffix: "", pro: "IMRO", cae: "545394335"},
{ fName: "Bryn", mName: "Troy", lName: "Evans", suffix: "", pro: "APRA", cae: "437473638"},
{ fName: "Kenichi", mName: "", lName: "Kikugawa", suffix: "", pro: "APRA", cae: "833138646"},
{ fName: "Jayden", mName: "B", lName: "Horner", suffix: "", pro: "APRA", cae: "743376627"},
{ fName: "Idar", mName: "", lName: "Andersen", suffix: "", pro: "TONO", cae: "519779109"},
{ fName: "Claudia", mName: "Regina Prates", lName: "Cimbleris", suffix: "", pro: "ASSIM", cae: "202634019"},
{ fName: "Albert", mName: "Fernandez", lName: "Ventura", suffix: "", pro: "SGAE", cae: "769.006.424"}
]

let composers = composerList.map((c) => {
    let fullName = c.fName + " ";
    if(c.mName.length > 0){
        fullName += c.mName + " ";
    }
    if(c.lName.length > 0){
        fullName += c.lName + " ";
    }
    if(c.suffix.length > 0){
        fullName += c.suffix + " ";
    }

    fullName = fullName.trim();

    return {fullName: fullName,
            fName: c.fName,
            mName: c.mName,
            lName: c.lName,
            suffix: c.suffix,
            cae: c.cae,
            pro: c.pro}
})

module.exports = composers;