const description = [
    "80's",
    "Abrasive",
    "Abstract",
    "Achievement",
    "Acid Jazz",
    "Acid Trip",
    "Acoustic",
    "Action",
    "Activity",
    "Adrenaline",
    "Advancing The Scene",
    "Adventure",
    "Advertisement",
    "Aggressive",
    "Agitated",
    "Airy",
    "Alarming",
    "Alternative Rock",
    "Ambient",
    "Americana",
    "Angelic",
    "Angry",
    "Animation Music",
    "Anthemic",
    "Anticipation",
    "Anxious",
    "Ascending",
    "Atmospheric",
    "Attitude",
    "Badass",
    "Ballad",
    "Baroque",
    "Bayou",
    "Beach",
    "Bed Mix",
    "Being Chased",
    "Big",
    "Bittersweet",
    "Blissful",
    "Blues",
    "Booming",
    "Bouncy",
    "Brat Pop",
    "Breezy",
    "Bright",
    "Brooding",
    "Building",
    "Bumpkin",
    "Calm",
    "Campy",
    "Carefree",
    "Cartoon",
    "Casual",
    "Catchy",
    "Catwalk",
    "Caution",
    "Cautious",
    "Celebrate",
    "Celebrating",
    "Celebration",
    "Chants",
    "Cheeky",
    "Cheesy",
    "Childlike",
    "Children",
    "Chill",
    "Chillwave",
    "Cinematic",
    "Classic Rock",
    "Classical",
    "Club",
    "Clumsy",
    "Cold",
    "Comedy",
    "Comical",
    "Coming Together",
    "Commercial",
    "Compelling",
    "Competition",
    "Concerned",
    "Confident",
    "Conflict",
    "Confrontation",
    "Confusion",
    "Cool",
    "Corny",
    "Corporate",
    "Cosmic",
    "Countdown",
    "Country",
    "Creepy",
    "Crime",
    "Curious",
    "Dance",
    "Dangerous",
    "Dark",
    "Decision Time",
    "Deep",
    "Delicate",
    "Delightful",
    "Depressed",
    "Despair",
    "Detective",
    "Determination",
    "Digital",
    "Disco",
    "Dissonant",
    "Distortion",
    "Distraught",
    "Distress",
    "Dj",
    "Documentary",
    "Down Tempo",
    "Drama",
    "Dramatic",
    "Dramedy",
    "Dreampop",
    "Dreamy",
    "Driving",
    "Drone",
    "Drum And Bass",
    "Dubstep",
    "Dynamic",
    "Eclectic",
    "Edgy",
    "Edm",
    "Eerie",
    "Electronic",
    "Elegant",
    "Emotional",
    "Energetic",
    "Energy",
    "Epic",
    "Escalating",
    "Ethereal",
    "Ethnic",
    "Evil",
    "Exciting",
    "Fairy Tale",
    "Fame",
    "Fanfare",
    "Fantasy",
    "Fast",
    "Fear",
    "Fearful",
    "Feel",
    "Good",
    "Festive",
    "Film Score",
    "Foreboding",
    "Frenzy",
    "Fun",
    "Funky",
    "Funny",
    "Future",
    "Futurebass",
    "Game Show",
    "Gentle",
    "Gimmicky",
    "Girls",
    "Girly",
    "Glam",
    "Gloomy",
    "Glory",
    "Glowing",
    "Goofy",
    "Graceful",
    "Grief",
    "Gritty",
    "Groovy",
    "Happy",
    "Haunting",
    "Healing",
    "Heartbeat",
    "Heartbreak",
    "Heartbreaking",
    "Heartfelt",
    "Heartwarming",
    "Heavy",
    "Heist",
    "Heroic",
    "Hip Hop",
    "Hip Hop Comedy",
    "Hip Hop Feel",
    "Hip Hop Suspense",
    "Hip Hop Tasking",
    "Hip Hop Tension",
    "Hip Hop Underscore",
    "Hip-hop Holiday",
    "Hollow",
    "Hope",
    "Hopeful",
    "Hopeless",
    "Horror",
    "House",
    "Hurt",
    "Hype",
    "Hypnotic",
    "Incognito",
    "Indie",
    "Industrial",
    "Innocent",
    "Insistent",
    "Inspiration",
    "Inspirational",
    "Inspired",
    "Inspiring",
    "Intense",
    "Intimidating",
    "Intrigue",
    "Introspective",
    "Investigative",
    "Island",
    "Jazzy",
    "Joyful",
    "Jungle",
    "Kids",
    "Laid Back",
    "Latin",
    "Lazy",
    "Light",
    "Lighthearted",
    "Lively",
    "Lonely",
    "Longing",
    "Lounge",
    "Love",
    "Lurking",
    "Machine",
    "Majestic",
    "Marching Band",
    "Meaningful",
    "Medical Drama",
    "Meditation",
    "Melancholy",
    "Mellow",
    "Melodramatic",
    "Menacing",
    "Military",
    "Minimal",
    "Mischief",
    "Modern Retro",
    "Money",
    "Montage",
    "Moody",
    "Motivating",
    "Motivation",
    "Motivational",
    "Mysterious",
    "Mystery",
    "Nature",
    "Neo-soul",
    "Neutral",
    "News",
    "Nostalgic",
    "Odd",
    "Old School",
    "Old Timey",
    "Ominous",
    "Optimistic",
    "Orchestral",
    "Organic",
    "Painful",
    "Party",
    "Patriotic",
    "Peaceful",
    "Pensive",
    "Percussive",
    "Pizzicato",
    "Playful",
    "Plotting",
    "Pop",
    "Pop Rock",
    "Positive",
    "Pounding",
    "Powerful",
    "Pride",
    "Proud",
    "Psychedelic",
    "Pulsating",
    "Pumping",
    "Quirky",
    "Rave",
    "Reflective",
    "Relaxed",
    "Relieving",
    "Restless",
    "Retro",
    "Reveal",
    "Rhythmic",
    "Risky",
    "Rnb",
    "Robotic",
    "Rocking",
    "Rollicking",
    "Romantic",
    "Rural",
    "Sad",
    "Scary",
    "Scheming",
    "Sci-fi",
    "Score",
    "Sensitive",
    "Sentimental",
    "Sexy",
    "Silly",
    "Sinister",
    "Smooth",
    "Sneaky",
    "Snooping",
    "Soft",
    "Soft Rock",
    "Somber",
    "Soothing",
    "Sophisticated",
    "Sorrow",
    "Sorrowful",
    "Soul",
    "Southern",
    "Spacey",
    "Sparse",
    "Spooky",
    "Sports",
    "Spy",
    "Stabs",
    "Stadium",
    "Stalking",
    "Storytelling",
    "Strange",
    "Strumming",
    "Subdued",
    "Surreal",
    "Suspense",
    "Suspenseful",
    "Swagger",
    "Swampy",
    "Sweeping",
    "Sweet",
    "Swing",
    "Synthpop",
    "Synthy",
    "Tasking",
    "Techno",
    "Technology",
    "Teen",
    "Tense",
    "Tension",
    "Thematic",
    "Thoughtful",
    "Threatening",
    "Thriller",
    "Touching",
    "Tragedy",
    "Tragic",
    "Trailer",
    "Training Sequence",
    "Trance",
    "Tranquil",
    "Trap",
    "Trap Tension",
    "Travel",
    "Trendy",
    "Tribal",
    "Trippy",
    "Triumphant",
    "Tropical",
    "Troubled",
    "Underscore",
    "Understated",
    "Uneasy",
    "Unsettling",
    "Upbeat",
    "Uplifting",
    "Uptempo",
    "Urban",
    "Urban Drama",
    "Urban Latin",
    "Urban Retro",
    "Urban Tension",
    "Urgency",
    "Urgent",
    "Vacation",
    "Vibes",
    "Video Game",
    "Vintage",
    "Wacky",
    "Walking",
    "War",
    "Warm",
    "Warning",
    "Weird",
    "Whimsical",
    "Whirling",
    "Wild",
    "Winning",
    "Wobble Bass",
    "Wonder",
    "Working Out",
    "Workout",
    "World",
    "World Music",
    "Worried",
    "Worry",
    "Yearning",
    "Yoga",
    "Youthful",
    "Zen",


]

description.sort();
export default description;