const description = [
    "Calm",
    "Happy",
    "Ambient",
    "Orchestral",
    "Heroic",
    "Adventure",
    "Preparation",
    "Comical",
    "Comedy",
    "Club",
    "Edm",
    "Urban",
    "Sci-fi",
    "World",
    "Tragic",
    "Tension",
    "Swing",
    "Tribal",
    "Somber",
    "Americana",
    "80's",
    "70's",
    "Adrenaline",
    "Anxious", 
    "Dark",
    "Horror",
    "Dramatic",
    "Hip Hop",
    "Electronica",
    "Majestic",
    "Meditation",
    "Montage",
    "Sneaky",
    "Sorrowful",
    "Soul",
    "Wacky",
    "Weird",
    "Latin",
    "Wobble Bass",
    "Suspenseful",
    "Bright",
    "Carefree",
    "Classical",
    "Nostalgic",
    "Light",
    "Laid Back",
    "Romantic",
    "Relaxed",
    "Reflective",
    "Warm",
    "Whimsical",
    "Alternative Rock",
    "Angry",
    "Creepy",
    "Feel Good",
    "Fun",
    "Upbeat",
    "Soothing",
    "Ominous",
    "Acoustic",
    "Activity",
    "Drama",
    "Driving",
    "Emotional",
    "Hearbreak",
    "Industrial",
    "Jazzy",
    "Kids",
    "Melancholy",
    "Nature",
    "Spooky",
    "Uneasy",
    "Zen",
    "Alarming",
    "Dreamy",
    "Groovy",
    "Gritty",
    "Rock",
    "Heavy Rock",
    "Blues",
    "Atmospheric",
    "Ambient",
    "High Energy",
    "Sentimental",
    "Light Hearted",
    "Despair",
    "Quirky",
    "Fanfare",
    "March"

]

description.sort();
export default description;