
let genreArray = [

"Blues / Blues",
"Contemporary Underscore / Action",
"Contemporary Underscore / Drones",
"Contemporary Underscore / Horror",
"Contemporary Underscore / Informational",
"Contemporary Underscore / Musical FX",
"Contemporary Underscore / Mystery",
"Contemporary Underscore / News",
"Contemporary Underscore / Oddities",
"Contemporary Underscore / Patriotic – Heroic",
"Contemporary Underscore / Poignant",
"Contemporary Underscore / Positivity",
"Contemporary Underscore / Rhythmic Beds",
"Contemporary Underscore / Romance",
"Contemporary Underscore / Sadness",
"Contemporary Underscore / Sci-Fi",
"Contemporary Underscore / Shifting Moods",
"Contemporary Underscore / Spiritual",
"Contemporary Underscore / Suspense",
"Contemporary Underscore / Tension",
"Contemporary Underscore / Themes",
"Contemporary Underscore / Triumphant",
"Country - Americana / Country-Americana",
"Dance / Breaks",
"Dance / Chill",
"Dance / EDM",
"Dance / Pop",
"Dance / Retro",
"Funk / ",
"Goofy – Comedic – Kids / ",
"Hip Hop / Chill – Lo Fi",
"Hip Hop / Contemporary",
"Hip Hop / Hick Hop",
"Hip Hop / Old School",
"Hip Hop / RnB – Neo Soul",
"Holiday / Contemporary",
"Holiday / Standards",
"Holiday / Traditional",
"Holiday / World",
"Jazz / Big Band",
"Jazz / Modern Retro",
"Jazz / Small Ensemble",
"Jazz / Smooth",
"Orchestral Underscore / Action",
"Orchestral Underscore / Adventurous",
"Orchestral Underscore / Classical",
"Orchestral Underscore / Golden Era Hollywood",
"Orchestral Underscore / Horror",
"Orchestral Underscore / Mystery",
"Orchestral Underscore / Poignant",
"Orchestral Underscore / Positivity ",
"Orchestral Underscore / Rhythmic Beds",
"Orchestral Underscore / Sadness",
"Orchestral Underscore / Shifting Moods",
"Orchestral Underscore / Suspense",
"Orchestral Underscore / Tension",
"Orchestral Underscore / Triumphant",
"Retro TV / Bumpers – Stingers",
"Retro TV / Mystery",
"Retro TV / Positivity",
"Retro TV / Rhythmic Beds",
"Retro TV / Suspense",
"Retro TV / Themes",
"Rock / 50's – 60's",
"Rock / 70's",
"Rock / 80's",
"Rock / Hard",
"Rock / Industrial",
"Rock / Pop",
"Solo Instruments / Ac Gtr",
"Solo Instruments / Ac Pno",
"Solo Instruments / Elec Gtr",
"Solo Instruments / Jazz",
"Solo Instruments / Misc",
"Solo Instruments / Orchestral",
"Stingers / Dance",
"Stingers / Gtr FX",
"Stingers / Hip Hop",
"Stingers / Hits",
"Stingers / Holiday",
"Stingers / Jazz",
"Stingers / Oddities",
"Stingers / Orchestral",
"Stingers / Poignant",
"Stingers / Positivity",
"Stingers / Rhythmic Beds",
"Stingers / Rock",
"Stingers / Suspense",
"Stingers / Swells",
"Stingers / World",
"World Music / Reggae - Ska",
"World Music / African",
"World Music / Asian",
"World Music / Australian",
"World Music / Caribbean – Island",
"World Music / European",
"World Music / Indian – Middle East",
"World Music / Latin",
"World Music / Native American",
"World Music / Reggaeton",
"World Music / Suspense",    
];

genreArray = genreArray.sort();

let genreObjArray = genreArray.map((g, index) => {return {genre: g, genreId: index + 1}})



export default genreObjArray;