
// This is the old genres names before the change. 
//  const genreArray = [
//      "Bumpers - Transitions / Bittersweet",
//      "Bumpers - Transitions / Dramatic",
//      "Bumpers - Transitions / Driving",
//      "Bumpers - Transitions / Electronic",
//      "Bumpers - Transitions / Guitar Fix",
//      "Bumpers - Transitions / Holiday",
//      "Bumpers - Transitions / Jazz",
//      "Bumpers - Transitions / Orchestral Dramatic",
//      "Bumpers - Transitions / Rhythmic",
//      "Bumpers - Transitions / Rock - Pop - Blues",
//      "Bumpers - Transitions / Strangeness",
//      "Bumpers - Transitions / Suspense",
//      "Bumpers - Transitions / Swells",
//      "Bumpers - Transitions / Urban",
//      "Bumpers - Transitions / World",
//      "Dance / Ambient - Down Tempo",
//      "Dance / Breaks",
//      "Dance / Dance Pop",
//      "Dance / Disco",
//      "Dance / Electronica",
//      "Dance / House",
//      "Dance / Nrg (rave-trance-techno)",
//      "Dance / Retro",
//      "Drama / Action - Power",
//      "Drama / Bittersweet",
//      "Drama / Carefree",
//      "Drama / Dark - Danger",
//      "Drama / Dramatic",
//      "Drama / Horror",
//      "Drama / Light Hearted",
//      "Drama / Mood Swings",
//      "Drama / Mystery - Suspense",
//      "Drama / Percussive Drama",
//      "Drama / Romance",
//      "Drama / Sci-fi",
//      "Drama / Solo Instruments - Acoustic Guitar",
//      "Drama / Solo Instruments - Electric Guitar",
//      "Drama / Solo Instruments - Other",
//      "Drama / Solo Instruments - Piano",
//      "Drama / Sorrow - Despair",
//      "Drama / Strangeness",
//      "Drama / Tension Builder",
//      "Drama / Thematic",
//      "Drama / Triumph - New Beginning",
//      "Drama Orchestral / Action - Power",
//      "Drama Orchestral / Adventure",
//      "Drama Orchestral / Bitter Sweet",
//      "Drama Orchestral / Carefree",
//      "Drama Orchestral / Classical",
//      "Drama Orchestral / Dark - Danger",
//      "Drama Orchestral / Dramatic",
//      "Drama Orchestral / Golden Era",
//      "Drama Orchestral / Horror",
//      "Drama Orchestral / Light Hearted",
//      "Drama Orchestral / Mood Swings",
//      "Drama Orchestral / Mystery - Suspense",
//      "Drama Orchestral / Percussive Drama",
//      "Drama Orchestral / Solo Instruments",
//      "Drama Orchestral / Sorrow - Despair",
//      "Drama Orchestral / Tension Builder",
//      "Drama Orchestral / Triumph - New Beginning",
//      "Hip-Hop Rnb / Gangsta-Playa-Pimp",
//      "Hip-Hop Rnb / Hip-hop",
//      "Hip-Hop Rnb / Ol skool",
//      "Hip-Hop Rnb / Rnb - Soft",
//      "Hip-Hop Rnb / Trip-Hop",
//      "Holiday / Contemporary",
//      "Holiday / Holiday Standards",
//      "Holiday / Public Domain Contemporary",
//      "Holiday / Public Domain Traditional",
//      "Holiday / Traditional",
//      "Holiday / World",
//      "Jazz / Big Band - Large Ensemble",
//      "Jazz / Jazz Rock",
//      "Jazz / Quartet - Small Ensemble",
//      "Jazz / Smooth Jazz",
//      "Jazz / Solo Jazz Instruments",
//      "Reggae - Ska / Reggae Ska",
//      "Retro Tv Land / Bumpers Stingers",
//      "Retro Tv Land / Dramatic",
//      "Retro Tv Land / Light Hearted",
//      "Retro Tv Land / Mystery - Suspense",
//      "Retro Tv Land / Rhythmic Beds",
//      "Retro Tv Land / Thematic",
//      "Rock - Blues - Funk / 50's and 60's",
//      "Rock - Blues - Funk / 70's",
//      "Rock - Blues - Funk / 80's",
//      "Rock - Blues - Funk / Blues",
//      "Rock - Blues - Funk / Edgy - Industrial",
//      "Rock - Blues - Funk / Funk",
//      "Rock - Blues - Funk / Heavy Rock",
//      "Rock - Blues - Funk / Pop Rock",
//      "Score Tools / Band Aids - Hits",
//      "Score Tools / Carefree",
//      "Score Tools / Dramatic",
//      "Score Tools / Driving",
//      "Score Tools / Drones - Textures",
//      "Score Tools / Jazzy",
//      "Score Tools / Musical Fx",
//      "Score Tools / Positive Sorrow",
//      "Score Tools / Rhythmic",
//      "Score Tools / Rock - Pop",
//      "Score Tools / Techno - Electronica",
//      "Score Tools / Urban",
//      "Specialty / Country - Americana",
//      "Specialty / Goofy - Comedic - Kids",
//      "Specialty / Hick Hop",
//      "Specialty / Informational",
//      "Specialty / News",
//      "Specialty / Patriotic - Heroic",
//      "Specialty / Spiritiual",
//      "Specialty / What Were They Thinking",
//      "Vocal Trax / Dance - Urban",
//      "Vocal Trax / Rock - Blues",
//      "Vocal Trax / World",
//      "World Music / Africa",
//      "World Music / Australian",
//      "World Music / Carribean - Island",
//      "World Music / Central European",
//      "World Music / Contemporary World",
//      "World Music / Dramatic World",
//      "World Music / Far East",
//      "World Music / Indi - Arab Nations",
//      "World Music / Latin",
//      "World Music / Native American",
//      "World Pop / African",
//      "World Pop / Eastern",
//      "World Pop / Island",
//      "World Pop / Latin",
//      "World Pop / Reggaeton"
// ]



const genreArray = [
    
"Contemporary Underscore / Poignant",
"Blues / Blues",
"Contemporary Underscore / Positivity",
"Country - Americana / Country-Americana",
"Dance / Chill",
"Dance / Breaks",
"Dance / Pop",
"Dance / Retro",
"Dance / EDM",
"Dance / EDM",
"Dance / EDM",
"Dance / Retro",
"Contemporary Underscore / Action",
"Contemporary Underscore / Poignant",
"Contemporary Underscore / Positivity",
"Contemporary Underscore / Tension",
"Contemporary Underscore / Positivity",
"Contemporary Underscore / Suspense",
"Contemporary Underscore / Horror",
"Contemporary Underscore / Positivity",
"Contemporary Underscore / Shifting Moods",
"Contemporary Underscore / Mystery",
"Contemporary Underscore / Mystery",
"Contemporary Underscore / Rhythmic Beds",
"Contemporary Underscore / Romance",
"Contemporary Underscore / Sci-Fi",
"Solo Instruments / Ac Gtr",
"Solo Instruments / Elec Gtr",
"Solo Instruments / Misc",
"Solo Instruments / Ac Pno",
"Contemporary Underscore / Sadness",
"Contemporary Underscore / Oddities",
"Contemporary Underscore / Tension",
"Contemporary Underscore / Themes",
"Contemporary Underscore / Triumphant",
"Contemporary Underscore / Suspense",
"Contemporary Underscore / Suspense",
"Contemporary Underscore / Drones",
"Contemporary Underscore / Rhythmic Beds",
"Funk / ",
"Goofy – Comedic – Kids / ",
"Hip Hop / Hick Hop",
"Hip Hop / Contemporary",
"Hip Hop / Contemporary",
"Hip Hop / Old School",
"Holiday / Standards",
"Holiday / Contemporary",
"Holiday / Standards",
"Holiday / Traditional",
"Holiday / Standards",
"Holiday / World",
"Contemporary Underscore / Informational",
"Jazz / Big Band",
"Jazz / Modern Retro",
"Jazz / Small Ensemble",
"Jazz / Smooth",
"Solo Instruments / Jazz",
"Contemporary Underscore / Musical FX",
"Contemporary Underscore / News",
"Orchestral Underscore / Action",
"Orchestral Underscore / Adventurous",
"Orchestral Underscore / Poignant",
"Orchestral Underscore / Positivity ",
"Orchestral Underscore / Classical",
"Orchestral Underscore / Tension",
"Orchestral Underscore / Suspense",
"Orchestral Underscore / Golden Era Hollywood",
"Orchestral Underscore / Horror",
"Orchestral Underscore / Positivity ",
"Orchestral Underscore / Shifting Moods",
"Orchestral Underscore / Mystery",
"Orchestral Underscore / Rhythmic Beds",
"Solo Instruments / Orchestral",
"Orchestral Underscore / Sadness",
"Orchestral Underscore / Tension",
"Orchestral Underscore / Triumphant",
"Contemporary Underscore / Patriotic – Heroic",
"World / Reggae - Ska",
"Retro TV / Suspense",
"Retro TV / Positivity",
"Retro TV / Mystery",
"Retro TV / Rhythmic Beds",
"Retro TV / Bumpers – Stingers",
"Retro TV / Themes",
"Hip Hop / RnB – Neo Soul",
"Rock / Pop",
"Rock / 50's – 60's",
"Rock / 70's",
"Rock / 80's",
"Rock / Hard",
"Rock / Industrial",
"Rock / Pop",
"Contemporary Underscore / Spiritual",
"Stingers / Poignant",
"Stingers / Suspense",
"Stingers / Suspense",
"Stingers / Dance",
"Stingers / Gtr FX",
"Stingers / Holiday",
"Stingers / Jazz",
"Stingers / Positivity",
"Stingers / Orchestral",
"Stingers / Rhythmic Beds",
"Stingers / Rock",
"Stingers / Oddities",
"Stingers / Suspense",
"Stingers / Swells",
"Stingers / Hip Hop",
"Stingers / World",
"Stingers / Hits",
"Dance / EDM",
"Hip Hop / Chill – Lo Fi",
"Hip Hop / Contemporary",
"Hip Hop / Contemporary",
"Rock / Pop",
"World Music / African",
"World Music / Australian",
"World Music / Caribbean – Island",
"World Music / European",
"World Music / Suspense",
"World Music / Asian",
"World Music / Indian – Middle East",
"World Music / Latin",
"World Music / Native American",
"World Music / African",
"World Music / Asian",
"World Music / Caribbean – Island",
"World Music / Latin",
"World Music / Reggaeton"
];

let genreObjArray = genreArray.map((g, index) => {return {genre: g, genreId: index + 1}})



export default genreObjArray;