 const genreArray = [
     "Bumpers - Transitions / Bittersweet",
     "Bumpers - Transitions / Dramatic",
     "Bumpers - Transitions / Driving",
     "Bumpers - Transitions / Electronic",
     "Bumpers - Transitions / Guitar Fix",
     "Bumpers - Transitions / Holiday",
     "Bumpers - Transitions / Jazz",
     "Bumpers - Transitions / Orchestral Dramatic",
     "Bumpers - Transitions / Rhythmic",
     "Bumpers - Transitions / Rock - Pop - Blues",
     "Bumpers - Transitions / Strangeness",
     "Bumpers - Transitions / Suspense",
     "Bumpers - Transitions / Swells",
     "Bumpers - Transitions / Urban",
     "Bumpers - Transitions / World",
     "Dance / Ambient - Down Tempo",
     "Dance / Breaks",
     "Dance / Dance Pop",
     "Dance / Disco",
     "Dance / Electronica",
     "Dance / House",
     "Dance / Nrg (rave-trance-techno)",
     "Dance / Retro",
     "Drama / Action - Power",
     "Drama / Bittersweet",
     "Drama / Carefree",
     "Drama / Dark - Danger",
     "Drama / Dramatic",
     "Drama / Horror",
     "Drama / Light Hearted",
     "Drama / Mood Swings",
     "Drama / Mystery - Suspense",
     "Drama / Percussive Drama",
     "Drama / Romance",
     "Drama / Sci-fi",
     "Drama / Solo Instruments - Acoustic Guitar",
     "Drama / Solo Instruments - Electric Guitar",
     "Drama / Solo Instruments - Other",
     "Drama / Solo Instruments - Piano",
     "Drama / Sorrow - Despair",
     "Drama / Strangeness",
     "Drama / Tension Builder",
     "Drama / Thematic",
     "Drama / Triumph - New Beginning",
     "Drama Orchestral / Action - Power",
     "Drama Orchestral / Adventure",
     "Drama Orchestral / Bitter Sweet",
     "Drama Orchestral / Carefree",
     "Drama Orchestral / Classical",
     "Drama Orchestral / Dark - Danger",
     "Drama Orchestral / Dramatic",
     "Drama Orchestral / Golden Era",
     "Drama Orchestral / Horror",
     "Drama Orchestral / Light Hearted",
     "Drama Orchestral / Mood Swings",
     "Drama Orchestral / Mystery - Suspense",
     "Drama Orchestral / Percussive Drama",
     "Drama Orchestral / Solo Instruments",
     "Drama Orchestral / Sorrow - Despair",
     "Drama Orchestral / Tension Builder",
     "Drama Orchestral / Triumph - New Beginning",
     "Hip-Hop Rnb / Gangsta-Playa-Pimp",
     "Hip-Hop Rnb / Hip-hop",
     "Hip-Hop Rnb / Ol skool",
     "Hip-Hop Rnb / Rnb - Soft",
     "Hip-Hop Rnb / Trip-Hop",
     "Holiday / Contemporary",
     "Holiday / Holiday Standards",
     "Holiday / Public Domain Contemporary",
     "Holiday / Public Domain Traditional",
     "Holiday / Traditional",
     "Holiday / World",
     "Jazz / Big Band - Large Ensemble",
     "Jazz / Jazz Rock",
     "Jazz / Quartet - Small Ensemble",
     "Jazz / Smooth Jazz",
     "Jazz / Solo Jazz Instruments",
     "Reggae - Ska / Reggae Ska",
     "Retro Tv Land / Bumpers Stingers",
     "Retro Tv Land / Dramatic",
     "Retro Tv Land / Light Hearted",
     "Retro Tv Land / Mystery - Suspense",
     "Retro Tv Land / Rhythmic Beds",
     "Retro Tv Land / Thematic",
     "Rock - Blues - Funk / 50's and 60's",
     "Rock - Blues - Funk / 70's",
     "Rock - Blues - Funk / 80's",
     "Rock - Blues - Funk / Blues",
     "Rock - Blues - Funk / Edgy - Industrial",
     "Rock - Blues - Funk / Funk",
     "Rock - Blues - Funk / Heavy Rock",
     "Rock - Blues - Funk / Pop Rock",
     "Score Tools / Band Aids - Hits",
     "Score Tools / Carefree",
     "Score Tools / Dramatic",
     "Score Tools / Driving",
     "Score Tools / Drones - Textures",
     "Score Tools / Jazzy",
     "Score Tools / Musical Fx",
     "Score Tools / Positive Sorrow",
     "Score Tools / Rhythmic",
     "Score Tools / Rock - Pop",
     "Score Tools / Techno - Electronica",
     "Score Tools / Urban",
     "Specialty / Country - Americana",
     "Specialty / Goofy - Comedic - Kids",
     "Specialty / Hick Hop",
     "Specialty / Informational",
     "Specialty / News",
     "Specialty / Patriotic - Heroic",
     "Specialty / Spiritiual",
     "Specialty / What Were They Thinking",
     "Vocal Trax / Dance - Urban",
     "Vocal Trax / Rock - Blues",
     "Vocal Trax / World",
     "World Music / Africa",
     "World Music / Australian",
     "World Music / Carribean - Island",
     "World Music / Central European",
     "World Music / Contemporary World",
     "World Music / Dramatic World",
     "World Music / Far East",
     "World Music / Indi - Arab Nations",
     "World Music / Latin",
     "World Music / Native American",
     "World Pop / African",
     "World Pop / Eastern",
     "World Pop / Island",
     "World Pop / Latin",
     "World Pop / Reggaeton"
]

let genreObjArray = genreArray.map((g, index) => {return {genre: g, genreId: index + 1}})



export default genreObjArray;