const instrumentArray = [
    "Piano",
    "Steel",
    "Harp",
    "Guitar",
    "Pad", 
    "Electric Guitar",
    "Acoustic Guitar",
    "Drums",
    "Synth",
    "Bass",
    "FX",
    "Flute",
    "Bells",
    "Synth Pads",
    "Organ", 
    "Electric Piano",
    "Steel",
    "French Horn",
    "Male Choir",
    "Plucked Strings",
    "Keys",
    "Kalimba",
    "Synth Harp",
    "Vocoder",
    "Toy Piano",
    "Synth Lead",
    "Bagpipes",
    "Violin", 
    "Upright Bass",
    "Cymbals", 
    "Strings",
    "Woodwinds",
    "Saxophone",
    "Timpani",
    "Piccolo",
    "English Horn",
    "Water Fx",
    "Vocoder",
    "Baritone Sax",
    "Alto Sax",
    "Gong",
    "FX",
    "Laugh",
    "Animal Sounds",
    "Female Vocals",
    "Children's Vocals",
    "Tuba",
    "Trumpet",
    "Rhodes",
    "Sitar",
    "Triangle",
    "Sleigh Bells",
    "Accordion",
    "Snare Drum",
    "Mandolin",
    "Harmonica",
    "Choir",
    "Oboe",
    "Horns",
    "Clarinet",
    "Bongos",
    "Glockenspiel",
    "Mallet",
    "Chimes",
    "Pizzicato Strings",
    "Drum Loop",
    "Claps",
    "Orchestra",
    "Pipe Organ",
    "Percussion",
    "Heartbeat",
    "Sweeps",
    "Bodhran",
    "Sorna",
    "Shehnai",
    "Qanun",
    "Autoharp",
    "Cajon",
    "Tanpura",
    "Cuica",
    "Flugelhorn",
    "Music Box",
    "Ocarina",
    "Mellotron",
    "BeatBox",
    "Santoor",
    "Bass Drum",

]

instrumentArray.sort();

export default instrumentArray;