const instrumentArray = [
    "Piano",
    "Steel",
    "Harp",
    "Guitar",
    "Pad",
    "Electric Guitar",
    "Acoustic Guitar",
    "Drums",
    "Synth",
    "Bass",
    "FX",
    "Flute",
    "Bells",
    "Synth Pads",
    "Organ",
    "Electric Piano",
    "Steel",
    "French Horn",
    "Male Choir",
    "Plucked Strings",
    "Keys",
    "Kalimba",
    "Synth Harp",
    "Vocoder",
    "Toy Piano",
    "Synth Lead",
    "Bagpipes",
    "Violin",
    "Upright Bass",
    "Cymbals",
    "Strings",
    "Woodwinds",
    "Saxophone",
    "Timpani",
    "Piccolo",
    "English Horn",
    "Water Fx",
    "Vocoder",
    "Baritone Sax",
    "Alto Sax",
    "Gong",
    "FX",
    "Laugh",
    "Animal Sounds",
    "Female Vocals",
    "Children's Vocals",
    "Tuba",
    "Trumpet",
    "Rhodes",
    "Sitar",
    "Triangle",
    "Sleigh Bells",
    "Accordion",
    "Snare Drum",
    "Mandolin",
    "Harmonica",
    "Choir",
    "Oboe",
    "Horns",
    "Clarinet",
    "Bongos",
    "Glockenspiel",
    "Mallet",
    "Chimes",
    "Pizzicato Strings",
    "Drum Loop",
    "Claps",
    "Orchestra",
    "Pipe Organ",
    "Percussion",
    "Heartbeat",
    "Sweeps",
    "Bodhran",
    "Sorna",
    "Shehnai",
    "Qanun",
    "Autoharp",
    "Cajon",
    "Tanpura",
    "Cuica",
    "Flugelhorn",
    "Music Box",
    "Ocarina",
    "Mellotron",
    "BeatBox",
    "Santoor",
    "Bass Drum",
    "808",
    "ACCORDION",
    "ACOUSTIC GUITAR",
    "ALTO SAX",
    "ANVIL",
    "ARPEGGIATED SYNTH",
    "BAGPIPES",
    "BANJO",
    "BASS",
    "BASSOON",
    "BEAT-BOX",
    "BELLS",
    "BONGOS",
    "BRASS",
    "CASTANETS",
    "CELESTE",
    "CELLO",
    "CHANTS",
    "CHIMES",
    "CHOIR",
    "CLAPS",
    "CLARINET",
    "CLAVINET",
    "Clicks",
    "CONGAS",
    "COWBELL",
    "CRASH",
    "CYMBAL SWELL",
    "CYMBALS",
    "DIDGERIDOO",
    "DJ SCRATCHES",
    "DOBRO",
    "DRONE",
    "DRUM ROLL",
    "DRUMS",
    "DUDUK",
    "DULCIMER",
    "ELECTRIC GUITAR",
    "ELECTRIC PIANO",
    "FEMALE VOCALS",
    "FIDDLE",
    "FLUTE",
    "FRENCH HORN",
    "FX",
    "GLOCKENSPIEL",
    "GONG",
    "Guiro",
    "GUITAR",
    "GUITAR FX",
    "HARMONICA",
    "HARP",
    "HARPSICHORD",
    "HI HATS",
    "HITS",
    "Horns",
    "JAW HARP",
    "KALIMBA",
    "KEYBOARD",
    "KICK",
    "KICK DRUM",
    "KOTO",
    "LUTE",
    "MALE VOCALS",
    "MALLET",
    "MANDOLIN",
    "MARIMBA",
    "Mellotron",
    "Metallophone",
    "MUTED GUITAR",
    "NYLON GUITAR",
    "OBOE",
    "ORCHESTRA",
    "ORGAN",
    "PAD",
    "PERCUSSION",
    "PIANO",
    "PITCHED HI HATS",
    "PITCHED PERCUSSION",
    "PITCHED SNARE",
    "PIZZICATO STRINGS",
    "RHODES",
    "RISER",
    "SAXOPHONE",
    "SAZ",
    "SHAKER",
    "SHAKUHACHI",
    "FLUTE",
    "SHAMISEN",
    "SITAR",
    "SLEIGH BELLS",
    "SLIDE GUITAR",
    "SNAP",
    "SNARE DRUM",
    "SNARE ROLL",
    "SPANISH GUITAR",
    "STABS",
    "STEEL DRUM",
    "STRINGS",
    "SYNTH",
    "SYNTH ARP",
    "SYNTH BASS",
    "SYNTH BELL",
    "SYNTH BRASS",
    "SYNTH CHOIR",
    "SYNTH DRUMS",
    "SYNTH EFFECTS",
    "SYNTH FLUTE",
    "SYNTH FX",
    "SYNTH GATE",
    "SYNTH HITS",
    "SYNTH HORN",
    "SYNTH LEAD",
    "SYNTH ORGAN",
    "SYNTH STRINGS",
    "SYNTH VOCALS",
    "TAIKO",
    "TAMBOURINE",
    "Tanpura",
    "TENOR SAX",
    "TIMBALES",
    "TIMPANI",
    "TOY PIANO",
    "TRIANGLE",
    "TROMBONE",
    "TRUMPET",
    "TUBA",
    "TURNTABLES",
    "UKULELE",
    "UPRIGHT BASS",
    "VIBRAPHONE",
    "VIOLIN",
    "Vocal Fx",
    "VOCALS",
    "VOCODER",
    "WAH WAH GUITAR",
    "Whistle",
    "WIND CHIMES",
    "WOOD BLOCK",
    "WOODWINDS",
    "WURLITZER",
    "XYLOPHONE",
    "ZITHER",
]



instrumentArray.sort();

export default instrumentArray;